### ISSUE TITLE
Not cryptographically random

### ISSUE THREAD

**Issue by markstos** [crypto-utils/rndm#1]
`Math.random()` is [not cryptographically random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random). It seems worth mentioning this in the README, or switching to a random number generator which is considered cryptographically random, such as [crypto.randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) in Node.js.

**Comment by jonathanong** [comment]
it says "not cryptographically secure" in the readme. should i change the wording to "random"?

**Comment by markstos** [comment]
Sorry I missed that. Sounds perfect.

**Comment by mikesamuel** [comment]
Why does the README usage example show it used for generating salts if the source of randomness is weak?

> var salt = rndm(16)

I ask because the widely used `csrf` library seems to be using this to generate salts.

https://github.com/pillarjs/csrf/blob/8183e7c880abee4c60a8557f2c506fe8e5867d93/index.js#L84

**Comment by markstos** [comment]
@mikesamuel Then perhaps `csrf` should be using secure-random-string or another module instead.

**Comment by mikesamuel** [comment]
@markstos Thanks for the response.  Re `csrf`, I think I was confused about what they meant by "salt".  IIUC, their salt could be a serial number since it's only there to prevent replay attacks, not to prevent an attacker amortizing brute forcing effort the way salts do in password systems.
