### ISSUE TITLE
[BUG] Uncaught AssertionError: false == true

### ISSUE THREAD

**Issue by trusktr** [crypto-utils/rndm#2]
This happens after I've required rndm, when I call rndm() for the first time:

```
Uncaught AssertionError: false == true
```

It might be in a dependency of rndm. It happens at a point in the code that looks like this:

``` js
    // 3. All of the following functions must throw an AssertionError
    // when a corresponding condition is not met, with a message that
    // may be undefined if not provided.  All assertion methods provide
    // both the actual and expected values to the assertion error for
    // display purposes.

    function fail(actual, expected, message, operator, stackStartFunction) {
      throw new assert.AssertionError({
        message: message,
        actual: actual,
        expected: expected,
        operator: operator,
        stackStartFunction: stackStartFunction
      });
    }
```

**Comment by jonathanong** [comment]
oh i need better error messages

**Comment by jonathanong** [comment]
29fd8a06cd486d16eff518414a6b774bc655f3ce you need to call `rndm(<number>)`, not with no arguments. if the error message works for you, please close :)

**Comment by trusktr** [comment]
Aah, that works. Is an error better than a default number?

/#!/JoePea

**Comment by jonathanong** [comment]
not sure what the default would be though

**Comment by trusktr** [comment]
Me neither. Maybe 10?

/#!/JoePea

**Comment by haoxins** [comment]
+1 add default `10`

**Comment by jonathanong** [comment]
@coderhaoxin added you to the org :)

**Comment by haoxins** [comment]
Got it, I'll set a default value later

**Comment by haoxins** [comment]
617def35f705ea869379363c6932766264e5d647
